openapi: 3.2.0
info:
  title: Postiz Swagger file Settings API
  description: API description
  version: '1.0'
  contact: {}
servers: []
tags:
- name: Settings
paths:
  /settings/team:
    get:
      operationId: SettingsController_getTeam
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - Settings
      summary: Settings controller get team
      x-summary-source: derived
    post:
      operationId: SettingsController_inviteTeamMember
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddTeamMemberDto'
      responses:
        '201':
          description: ''
      tags:
      - Settings
      summary: Settings controller invite team member
      x-summary-source: derived
  /settings/team/add:
    post:
      operationId: SettingsController_addTeamMember
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdminAddTeamMemberDto'
      responses:
        '201':
          description: ''
      tags:
      - Settings
      summary: Settings controller add team member
      x-summary-source: derived
  /settings/team/{id}:
    delete:
      operationId: SettingsController_deleteTeamMember
      parameters:
      - name: id
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Settings
      summary: Settings controller delete team member
      x-summary-source: derived
  /settings/shortlink:
    get:
      operationId: SettingsController_getShortlinkPreference
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - Settings
      summary: Settings controller get shortlink preference
      x-summary-source: derived
    post:
      operationId: SettingsController_updateShortlinkPreference
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShortlinkPreferenceDto'
      responses:
        '201':
          description: ''
      tags:
      - Settings
      summary: Settings controller update shortlink preference
      x-summary-source: derived
components:
  schemas:
    AddTeamMemberDto:
      type: object
      properties: {}
    ShortlinkPreferenceDto:
      type: object
      properties: {}
    AdminAddTeamMemberDto:
      type: object
      properties: {}
