openapi: 3.2.0
info:
  title: Postiz Swagger file Third Party API
  description: API description
  version: '1.0'
  contact: {}
servers: []
tags:
- name: Third Party
paths:
  /third-party/list:
    get:
      operationId: ThirdPartyController_getThirdPartyList
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - Third Party
      summary: Third party controller get third party list
      x-summary-source: derived
  /third-party:
    get:
      operationId: ThirdPartyController_getSavedThirdParty
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - Third Party
      summary: Third party controller get saved third party
      x-summary-source: derived
  /third-party/{id}:
    delete:
      operationId: ThirdPartyController_deleteById
      parameters:
      - name: id
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Third Party
      summary: Third party controller delete by id
      x-summary-source: derived
  /third-party/{id}/submit:
    post:
      operationId: ThirdPartyController_generate
      parameters:
      - name: id
        required: true
        in: path
        schema:
          type: string
      responses:
        '201':
          description: ''
      tags:
      - Third Party
      summary: Third party controller generate
      x-summary-source: derived
  /third-party/function/{id}/{functionName}:
    post:
      operationId: ThirdPartyController_callFunction
      parameters:
      - name: id
        required: true
        in: path
        schema:
          type: string
      - name: functionName
        required: true
        in: path
        schema:
          type: string
      responses:
        '201':
          description: ''
      tags:
      - Third Party
      summary: Third party controller call function
      x-summary-source: derived
  /third-party/{id}/import:
    post:
      operationId: ThirdPartyController_importMedia
      parameters:
      - name: id
        required: true
        in: path
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImportMediaDto'
      responses:
        '201':
          description: ''
      tags:
      - Third Party
      summary: Third party controller import media
      x-summary-source: derived
  /third-party/{identifier}:
    post:
      operationId: ThirdPartyController_addApiKey
      parameters:
      - name: identifier
        required: true
        in: path
        schema:
          type: string
      responses:
        '201':
          description: ''
      tags:
      - Third Party
      summary: Third party controller add api key
      x-summary-source: derived
components:
  schemas:
    ImportMediaDto:
      type: object
      properties: {}
