openapi: 3.2.0
info:
  title: Postiz Swagger file User API
  description: API description
  version: '1.0'
  contact: {}
servers: []
tags:
- name: User
paths:
  /user/chatbase-token:
    get:
      operationId: UsersController_getChatbaseToken
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - User
  /user/agent-media-sso:
    get:
      operationId: UsersController_getAgentMediaSsoUrl
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - User
  /user/self:
    get:
      operationId: UsersController_getSelf
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - User
  /user/personal:
    get:
      operationId: UsersController_getPersonalInformation
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - User
    post:
      operationId: UsersController_changePersonal
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDetailDto'
      responses:
        '201':
          description: ''
      tags:
      - User
  /user/impersonate:
    get:
      operationId: UsersController_getImpersonate
      parameters:
      - name: name
        required: true
        in: query
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - User
    post:
      operationId: UsersController_setImpersonate
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - User
  /user/switch:
    post:
      operationId: UsersController_switchUser
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - User
  /user/email-notifications:
    get:
      operationId: UsersController_getEmailNotifications
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - User
    post:
      operationId: UsersController_updateEmailNotifications
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailNotificationsDto'
      responses:
        '201':
          description: ''
      tags:
      - User
  /user/api-key/rotate:
    post:
      operationId: UsersController_rotateApiKey
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - User
  /user/subscription:
    get:
      operationId: UsersController_getSubscription
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - User
  /user/subscription/tiers:
    get:
      operationId: UsersController_tiers
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - User
  /user/join-org:
    post:
      operationId: UsersController_joinOrg
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - User
  /user/organizations:
    get:
      operationId: UsersController_getOrgs
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - User
  /user/change-org:
    post:
      operationId: UsersController_changeOrg
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - User
  /user/logout:
    post:
      operationId: UsersController_logout
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - User
  /user/t:
    post:
      operationId: UsersController_trackEvent
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - User
components:
  schemas:
    EmailNotificationsDto:
      type: object
      properties: {}
    UserDetailDto:
      type: object
      properties: {}
