openapi: 3.2.0
info:
  title: Postiz Swagger file Copilot API
  description: API description
  version: '1.0'
  contact: {}
servers: []
tags:
- name: Copilot
paths:
  /copilot/chat:
    post:
      operationId: CopilotController_chatAgent
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - Copilot
      summary: Copilot controller chat agent
      x-summary-source: derived
  /copilot/agent:
    post:
      operationId: CopilotController_agent
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - Copilot
      summary: Copilot controller agent
      x-summary-source: derived
  /copilot/credits:
    get:
      operationId: CopilotController_calculateCredits
      parameters:
      - name: type
        required: true
        in: query
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Copilot
      summary: Copilot controller calculate credits
      x-summary-source: derived
  /copilot/{thread}/list:
    get:
      operationId: CopilotController_getMessagesList
      parameters:
      - name: thread
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Copilot
      summary: Copilot controller get messages list
      x-summary-source: derived
  /copilot/list:
    get:
      operationId: CopilotController_getList
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - Copilot
      summary: Copilot controller get list
      x-summary-source: derived
