openapi: 3.2.0
info:
  title: Postiz Swagger file Public API
  description: API description
  version: '1.0'
  contact: {}
servers: []
tags:
- name: Public API
paths:
  /public/v1/upload:
    post:
      operationId: PublicIntegrationsController_uploadSimple
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - Public API
      summary: Public integrations controller upload simple
      x-summary-source: derived
  /public/v1/upload-from-url:
    post:
      operationId: PublicIntegrationsController_uploadsFromUrl
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UploadDto'
      responses:
        '201':
          description: ''
      tags:
      - Public API
      summary: Public integrations controller uploads from url
      x-summary-source: derived
  /public/v1/find-slot/{id}:
    get:
      operationId: PublicIntegrationsController_findSlotIntegration
      parameters:
      - name: id
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Public API
      summary: Public integrations controller find slot integration
      x-summary-source: derived
  /public/v1/posts:
    get:
      operationId: PublicIntegrationsController_getPosts
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - Public API
      summary: Public integrations controller get posts
      x-summary-source: derived
    post:
      operationId: PublicIntegrationsController_createPost
      parameters: []
      responses:
        '201':
          description: ''
      tags:
      - Public API
      summary: Public integrations controller create post
      x-summary-source: derived
  /public/v1/posts/{id}:
    delete:
      operationId: PublicIntegrationsController_deletePost
      parameters:
      - name: id
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Public API
      summary: Public integrations controller delete post
      x-summary-source: derived
  /public/v1/posts/group/{group}:
    delete:
      operationId: PublicIntegrationsController_deletePostByGroup
      parameters:
      - name: group
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Public API
      summary: Public integrations controller delete post by group
      x-summary-source: derived
  /public/v1/is-connected:
    get:
      operationId: PublicIntegrationsController_getActiveIntegrations
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - Public API
      summary: Public integrations controller get active integrations
      x-summary-source: derived
  /public/v1/groups:
    get:
      operationId: PublicIntegrationsController_listGroups
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - Public API
      summary: Public integrations controller list groups
      x-summary-source: derived
  /public/v1/integrations:
    get:
      operationId: PublicIntegrationsController_listIntegration
      parameters:
      - name: group
        required: true
        in: query
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Public API
      summary: Public integrations controller list integration
      x-summary-source: derived
  /public/v1/social/{integration}:
    get:
      operationId: PublicIntegrationsController_getIntegrationUrl
      parameters:
      - name: integration
        required: true
        in: path
        schema:
          type: string
      - name: refresh
        required: true
        in: query
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Public API
      summary: Public integrations controller get integration url
      x-summary-source: derived
  /public/v1/notifications:
    get:
      operationId: PublicIntegrationsController_getNotifications
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - Public API
      summary: Public integrations controller get notifications
      x-summary-source: derived
  /public/v1/generate-video:
    post:
      operationId: PublicIntegrationsController_generateVideo
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VideoDto'
      responses:
        '201':
          description: ''
      tags:
      - Public API
      summary: Public integrations controller generate video
      x-summary-source: derived
  /public/v1/video/function:
    post:
      operationId: PublicIntegrationsController_videoFunction
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VideoFunctionDto'
      responses:
        '201':
          description: ''
      tags:
      - Public API
      summary: Public integrations controller video function
      x-summary-source: derived
  /public/v1/integrations/{id}:
    delete:
      operationId: PublicIntegrationsController_deleteChannel
      parameters:
      - name: id
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Public API
      summary: Public integrations controller delete channel
      x-summary-source: derived
  /public/v1/integration-settings/{id}:
    get:
      operationId: PublicIntegrationsController_getIntegrationSettings
      parameters:
      - name: id
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Public API
      summary: Public integrations controller get integration settings
      x-summary-source: derived
  /public/v1/posts/{id}/missing:
    get:
      operationId: PublicIntegrationsController_getMissingContent
      parameters:
      - name: id
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Public API
      summary: Public integrations controller get missing content
      x-summary-source: derived
  /public/v1/posts/{id}/settings:
    put:
      operationId: PublicIntegrationsController_updatePostSettings
      parameters:
      - name: id
        required: true
        in: path
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePostSettingsDto'
      responses:
        '200':
          description: ''
      tags:
      - Public API
      summary: Public integrations controller update post settings
      x-summary-source: derived
  /public/v1/posts/{id}/status:
    put:
      operationId: PublicIntegrationsController_changePostStatus
      parameters:
      - name: id
        required: true
        in: path
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePostStatusDto'
      responses:
        '200':
          description: ''
      tags:
      - Public API
      summary: Public integrations controller change post status
      x-summary-source: derived
  /public/v1/posts/{id}/release-id:
    put:
      operationId: PublicIntegrationsController_updateReleaseId
      parameters:
      - name: id
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Public API
      summary: Public integrations controller update release id
      x-summary-source: derived
  /public/v1/analytics/{integration}:
    get:
      operationId: PublicIntegrationsController_getAnalytics
      parameters:
      - name: integration
        required: true
        in: path
        schema:
          type: string
      - name: date
        required: true
        in: query
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Public API
      summary: Public integrations controller get analytics
      x-summary-source: derived
  /public/v1/analytics/post/{postId}:
    get:
      operationId: PublicIntegrationsController_getPostAnalytics
      parameters:
      - name: postId
        required: true
        in: path
        schema:
          type: string
      - name: date
        required: true
        in: query
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Public API
      summary: Public integrations controller get post analytics
      x-summary-source: derived
  /public/v1/integration-trigger/{id}:
    post:
      operationId: PublicIntegrationsController_triggerIntegrationTool
      parameters:
      - name: id
        required: true
        in: path
        schema:
          type: string
      responses:
        '201':
          description: ''
      tags:
      - Public API
      summary: Public integrations controller trigger integration tool
      x-summary-source: derived
components:
  schemas:
    UploadDto:
      type: object
      properties: {}
    ChangePostStatusDto:
      type: object
      properties: {}
    UpdatePostSettingsDto:
      type: object
      properties: {}
    VideoDto:
      type: object
      properties: {}
    VideoFunctionDto:
      type: object
      properties: {}
