openapi: 3.2.0
info:
  title: Postiz Swagger file Sets API
  description: API description
  version: '1.0'
  contact: {}
servers: []
tags:
- name: Sets
paths:
  /sets:
    get:
      operationId: SetsController_getSets
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - Sets
      summary: Sets controller get sets
      x-summary-source: derived
    post:
      operationId: SetsController_createASet
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetsDto'
      responses:
        '201':
          description: ''
      tags:
      - Sets
      summary: Sets controller create ASet
      x-summary-source: derived
    put:
      operationId: SetsController_updateSet
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSetsDto'
      responses:
        '200':
          description: ''
      tags:
      - Sets
      summary: Sets controller update set
      x-summary-source: derived
  /sets/{id}:
    delete:
      operationId: SetsController_deleteSet
      parameters:
      - name: id
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Sets
      summary: Sets controller delete set
      x-summary-source: derived
components:
  schemas:
    SetsDto:
      type: object
      properties: {}
    UpdateSetsDto:
      type: object
      properties: {}
