openapi: 3.2.0
info:
  title: Postiz Swagger file Announcements API
  description: API description
  version: '1.0'
  contact: {}
servers: []
tags:
- name: Announcements
paths:
  /announcements:
    get:
      operationId: AnnouncementsController_getAnnouncements
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - Announcements
      summary: Announcements controller get announcements
      x-summary-source: derived
    post:
      operationId: AnnouncementsController_createAnnouncement
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnnouncementDto'
      responses:
        '201':
          description: ''
      tags:
      - Announcements
      summary: Announcements controller create announcement
      x-summary-source: derived
  /announcements/{id}:
    delete:
      operationId: AnnouncementsController_deleteAnnouncement
      parameters:
      - name: id
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Announcements
      summary: Announcements controller delete announcement
      x-summary-source: derived
components:
  schemas:
    AnnouncementDto:
      type: object
      properties: {}
