openapi: 3.2.0
info:
  title: Postiz Swagger file Signatures API
  description: API description
  version: '1.0'
  contact: {}
servers: []
tags:
- name: Signatures
paths:
  /signatures:
    get:
      operationId: SignatureController_getSignatures
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - Signatures
      summary: Signature controller get signatures
      x-summary-source: derived
    post:
      operationId: SignatureController_createSignature
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignatureDto'
      responses:
        '201':
          description: ''
      tags:
      - Signatures
      summary: Signature controller create signature
      x-summary-source: derived
  /signatures/default:
    get:
      operationId: SignatureController_getDefaultSignature
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - Signatures
      summary: Signature controller get default signature
      x-summary-source: derived
  /signatures/{id}:
    delete:
      operationId: SignatureController_deleteSignature
      parameters:
      - name: id
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Signatures
      summary: Signature controller delete signature
      x-summary-source: derived
    put:
      operationId: SignatureController_updateSignature
      parameters:
      - name: id
        required: true
        in: path
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignatureDto'
      responses:
        '200':
          description: ''
      tags:
      - Signatures
      summary: Signature controller update signature
      x-summary-source: derived
components:
  schemas:
    SignatureDto:
      type: object
      properties: {}
